# docker-compose.yml

version: '3.8'
services:
  api:
      build: .
      ports:
        - '3000:3000'
      environment:
        - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/median?schema=public
      depends_on:
        - postgres

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=median
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  prisma-studio:
    build: .
    command: npx prisma studio --port 5555 --browser none
    ports:
      - '5555:5555'
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/median?schema=public
    depends_on:
      - postgres

volumes:
  postgres:

